Traceback (most recent call last):
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/.local/share/pdm/python/cpython@3.9.19/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/myst-nb-json/myst-nb-json/.venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from typing import Optional
from pydantic import BaseModel


class Model2(BaseModel):
    key21: int
    key22: bool
    key23: Optional[str]


class ExampleModel(BaseModel):
    key1: str
    key2: Model2
    key3: list[str]
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Optional
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpydantic[39;00m [38;5;28;01mimport[39;00m BaseModel
[1;32m      5[0m [38;5;28;01mclass[39;00m [38;5;21;01mModel2[39;00m(BaseModel):
[1;32m      6[0m     key21: [38;5;28mint[39m

[0;31mModuleNotFoundError[0m: No module named 'pydantic'

